import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.tsx";
import { createRouter, RouterProvider } from "@tanstack/react-router";
import { useAuth, ClerkProvider } from "@clerk/react";
import { routeTree } from "./routeTree.gen"; // auto-generated by the plugin

const router = createRouter({
  routeTree,
  context: { auth: undefined! }, // populated at render time
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

function InnerApp() {
  const auth = useAuth();
  return <RouterProvider router={router} context={{ auth }} />;
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <ClerkProvider publishableKey={import.meta.env.VITE_CLERK_PUBLISHABLE_KEY}>
      <InnerApp />
    </ClerkProvider>
  </StrictMode>
);
