// This file has been generated by Specta. Do not edit this file manually.
export type Estimation = {
	predicted_minutes: number,
	confidence_score: number,
	last_updated: string,
};

export type Task = {
	id: TaskId,
	title: string,
	description: string,
	status: TaskStatus,
	due_date: string | null,
	estimation: Estimation | null,
	parent_id: TaskId | null,
	metadata: TaskMetadata,
};

export type TaskDraft = {
	title: string,
	description: string,
	due_date: string | null,
	estimation: Estimation | null,
	parent_id: TaskId,
	metadata: TaskMetadata,
};

export type TaskId = number;

export type TaskMetadata = {
	tags: string[],
	derived_from: string,
};

export type TaskStatus = "PendingReview" | "Todo" | "InProgress" | "Completed" | "Archived";
